### ISSUE TITLE
Support of Traverse at PU

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#111]
@lsawade to provide details about how to access the machine.

**Comment by andre-merzky** [comment]
We have preliminary support for Traverse now.  I still need to check GPU support though - otherwise the machine behaved fairly well :-D  

The PRs in RS and RP are here:
  - RS: https://github.com/radical-cybertools/radical.saga/pull/778
  - RP: https://github.com/radical-cybertools/radical.pilot/pull/2112

**Comment by mturilli** [comment]
Done!
