### ISSUE TITLE
Document data staging with examples

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#114]

**Comment by lsawade** [comment]
# Downloading data from within workflow

One of the future goals of my workflow is whenever an initial solution for an 
earthquake mechanism is available to run an inversion on this new earthquake. 
For that workflow it would be of supreme convenience if the data download could
happen inside the workflow.

## Workflow 

The workflow can be split into multiple stages.

1. Create database structure for the earthquake and data to be produced
2. Downloading the observed data
3. Simulations (computationally heavy part)
4. Processing of the data
5. Inversion of the data.

We want to potentially do multiple iterations of stages 3-5, which would
raise the computational cost by a factor of the iterations, but we are not there
yet.

## Downloading data

Ideally, I would like that all the above stages are included in a pipeline.
One pipeline for each earthquake, meaning, multiple pipelines in a workflow.

This would mean that the earthquake data has to be downloaded in a 
`Task`/`Stage`. But I know that generally the `Task`s are sent to the compute
nodes which usually do not have an internet connection. That means that the task
would somehow have to communicate with the `manager` to move that task to the
head node.

One of the script that I run is basically `./downloaddata.sh <eq_id>` and it does
the thing. It just can't do it from the compute node. In my case, both head and 
compute node have access to the same drives. So, I wouldn't have to send data
anywhere. 

[This bit might not be too important:] Since I would like that to be done for 
many earthquakes, it also has to happen
more or less dynamically. It would be nice if it can be allocated to the
different cores on the head node, so that downloads for different earthquakes
can happen in parallel.

Thanks in advance!

Let me know what you think.

**Comment by mturilli** [comment]
https://github.com/radical-collaboration/hpc-workflows/issues/112#issuecomment-612153304
