### ISSUE TITLE
Fatal error at the last substage of preprocessing

### ISSUE THREAD

**Issue by vivek-bala** [radical-collaboration/hpc-workflows#19]
I get the following error and output while doing "pypaw-sum_adjoint_asdf":

STDERR:
```
Traceback (most recent call last):
  File "/work/02734/vivek91/modules/miniconda2/envs/pypaw_env/bin/pypaw-sum_adjoint_asdf", line 11, in <module>
    load_entry_point('pypaw', 'console_scripts', 'pypaw-sum_adjoint_asdf')()
  File "/work/02734/vivek91/modules/pypaw/pypaw/bins/sum_adjoint_asdf.py", line 29, in main
    job.smart_run()
  File "/work/02734/vivek91/modules/pypaw/pypaw/sum_adjoint.py", line 287, in smart_run
    self.check_all_event_info()
  File "/work/02734/vivek91/modules/pypaw/pypaw/sum_adjoint.py", line 215, in check_all_event_info
    check_event_information_in_asdf_files(asdf_files)
  File "/work/02734/vivek91/modules/pypaw/pypaw/sum_adjoint.py", line 109, in check_event_information_in_asdf_files
    origin = event_base[0].preferred_origin()
  File "/work/02734/vivek91/modules/miniconda2/envs/pypaw_env/lib/python2.7/site-packages/obspy/core/event/catalog.py", line 162, in __getitem__
    return self.events.__getitem__(index)
IndexError: list index out of range
[c557-902.stampede.tacc.utexas.edu:mpispawn_0][child_handler] MPI process (rank: 0, pid: 97379) exited with status 1
```

STDOUT:
```
==================== Path information ====================
{u'input_file': {u'17_40': {u'asdf_file': u'/work/02734/vivek91/DATA_RADICAL/adjoint/C201002060444A.17_40.adjoint.h5',
                            u'weight_file': u'/work/02734/vivek91/DATA_RADICAL/weight/C201002060444A.17_40/C201002060444A.17_40.weight.json'},
                 u'40_100': {u'asdf_file': u'/work/02734/vivek91/DATA_RADICAL/adjoint/C201002060444A.40_100.adjoint.h5',
                             u'weight_file': u'/work/02734/vivek91/DATA_RADICAL/weight/C201002060444A.40_100/C201002060444A.40_100.weight.json'},
                 u'90_250': {u'asdf_file': u'/work/02734/vivek91/DATA_RADICAL/adjoint/C201002060444A.90_250.adjoint.h5',
                             u'weight_file': u'/work/02734/vivek91/DATA_RADICAL/weight/C201002060444A.90_250/C201002060444A.90_250.weight.json'}},
 u'output_file': u'/work/02734/vivek91/DATA_RADICAL/adjoint_sum/C201002060444A.adjoint.h5'}
==================== Param information ====================
{'rotate_flag': True}
```

You can reproduce (as well as run the previous substages) by following the instructions at ```https://github.com/radical-collaboration/hpc-workflows/tree/master/scripts/regional_Greece_small/preprocessing```

Note: The input path and parameter files are located at "/work/02734/vivek91/modules/simpy/examples/titan_global_inv" on Stampede. The output is generated at "/work/02734/vivek91/DATA_RADICAL" on Stampede. The associated pilot sandbox (which contains only the standard output and standard error) is "/work/02734/vivek91/radical.pilot.sandbox/rp.session.js-172-77.jetstream-cloud.org.vivek91.017281.0012-pilot.0000"

All the required permissions should be set. Let me know otherwise.

**Comment by wjlei1990** [comment]
Hi Vivek,

Following our last emails for data processing on RHEA, the directories you mentioned:
```
PBS script: /lustre/atlas/scratch/vivekb/bip149/pypaw-tools/run.pbs
Stderr: /lustre/atlas/scratch/vivekb/bip149/pypaw-tools/test.o243315
Data location: /lustre/atlas/scratch/vivekb/bip149/DATA_RADICAL
Parameters/Path files: /lustre/atlas/scratch/vivekb/bip149/simpy/examples/titan_global_inv
```
I am not able to get access to them due to `permission denied`.

I did a quick check on the directory `/lustre/atlas1/bip149/world-shared/DATA_RADICAL`. All the processed observed file contains no waveform data(so the file size is very small). For the processed synthetic data, there is only one file that is valid, `C201002060444A.proc_synt_90_250.h5`.

It would be great if we can get access to the log files(or your running directory).

**Comment by vivek-bala** [comment]
Hey Wenjie,

I moved all the data and scripts to the following location:

```
PBS script: /lustre/atlas1/bip149/world-shared/pypaw-tools/run.pbs
Stderr: /lustre/atlas1/bip149/world-shared/pypaw-tools/test.o243315
Data location: /lustre/atlas1/bip149/world-shared/DATA_RADICAL
Parameters/Path files: /lustre/atlas1/bip149/world-shared/simpy/examples/titan_global_inv
```

You should have permissions to access them.

**Comment by wjlei1990** [comment]
I think the problem is:
```
#mpirun -np 16 pypaw-process_asdf -f /lustre/atlas1/bip149/world-shared/simpy/examples/titan_global_inv/paths/ProcessObserved/C201002060444A.proc_obsd_17_40.path.json -p /lustre/atlas1/bip149/world-shared/simpy/examples/titan_global_inv/params/ProcessObserved/proc_obsd.17_40.param.yml &
```

On rhea, you need to specify the node ids to manually launch multiple jobs...Otherwise, all the jobs actually are running on the same node. So basically everything cramped together and become very very slow.

To launch jobs correctly, we do:
```
nodenames=($(uniq $PBS_NODEFILE))
node_id=0
mpirun -n 16 -host ${nodenames[$node_id]} pypaw-process_asdf -f ... -p ... &
node_id=$(( $node_id + 1 ))
...
```
It takes us very long time to figure out this issue.

I think your settings are correct. I also tried running a few jobs using your parameter file. Though I don't have access to your raw observed and synthetic data, I copied mine(since you got those files from me).

I think if you fix the issue and run the jobs again, you will get right results. But let's see.

**Comment by vivek-bala** [comment]
I will replicate the changes you suggested and try again. The hostname list is by default specified when run through Radical Pilot so we don't need any new implementation on the RP for this.

**Comment by wjlei1990** [comment]
Hi Vivke, Did you get a chance to try it again?

**Comment by vivek-bala** [comment]
I tried it again and got it to work last week. I had to reinstall since some files got purged, I think I might have messed that up. @wjlei1990 can we give it a try together?

**Comment by wjlei1990** [comment]
Sure...Let's talk during today's meeting.

**Comment by vivek-bala** [comment]
Hey Wenjie, I basically reinstalled everything and compiled my own hdf5-parallel. I'm able to go ahead with execution  now. I ran each stage one at a time and things seem to be ok till the last stage. I am actually getting the original error again. Maybe I didn't check the log correctly in my last run, apologies. Just to be sure I installed using the following instructions: https://github.com/radical-collaboration/hpc-workflows/blob/master/docs/pypaw_installation.md.

I checked the size of the files up till the adjoint stage and they seem to be much bigger than eariler.
```
$ du -sh */
905M	adjoint/
4.0K  	adjoint_sum/
5.1M	measure/
3.6G	proc_obsd/
1.9G	proc_synt/
24G 	raw_obsd/
3.1G	raw_synt/
6.3M	stations/
740K	weight/
17M	window/
```

I have put all the files in the following directories:
```
PBS script: /lustre/atlas/world-shared/bip149/pypaw-tools/run.pbs
Stderr, Stdout logs: /lustre/atlas/world-shared/bip149/pypaw-tools/*.log
Data location: /lustre/atlas/world-shared/bip149/DATA_RADICAL
Parameters/Path files: /lustre/atlas/world-shared/bip149/simpy/examples/titan_global_inv
```

Let me know how I can help debug.

**Comment by wjlei1990** [comment]
Hi Vivek,

I looked through the output files and the workflow get stuck in the adjoint source generation. I think the situation is much better than last time...It at least get a lot of steps done.

In the adjoint source file, the event information is missing so when we add them up, the program pops out the error.

I am not sure what exactly caused the error. But I will take further look into them tomorrow.

Best,
Wenjie

**Comment by wjlei1990** [comment]
Hi Vevik,

It is really a very weird issue which I can not duplicate.

I am pretty sure the `adjoint` file you generated missing the event information inside it but I am not totally sure why it happens.

So I copied `proc_obsd`, `proc_synt` and `window` from your directory and try to generate the adjoint file. The output adjoint file is good. I also do the sum adjoint and it works. That is to say, I used your file as input and succesfully run to the end. I also compared my output file with yours...My `adjoint` files are slightly larger than yours due to the event information.

My run dir is:
```
/lustre/atlas1/geo111/world-shared/wenjie/DATA_RADICAL/data_processing
```
I put path file, param file, data file and pbs file in that dir.

One suggestion, could you clean the dir `adjoint` and `adjoint_sum` and rerun the script again?

**Comment by vivek-bala** [comment]
Hmmm. Can you check if my installation is sufficient? Maybe it is versioning issue of some of the tools?

My installation instructions are here: https://github.com/radical-collaboration/hpc-workflows/blob/master/docs/pypaw_installation.md

Note that I have version 3.4.1 of flake8 and custom compiled hdf5 based on the instructions at https://github.com/wjlei1990/pypaw/blob/master/INSTALL.md.

Meanwhile I'll rerun it now.

**Comment by wjlei1990** [comment]
I can't see any issues with the installation...If the installation is wrong, you won't get to this step, I guess...

Flake8 should not be a issue..It is a package that checks the code format...

**Comment by vivek-bala** [comment]
I think you might have already looked at this. But just to be sure. I am noticing some messages in the log file for the adjoint step like the following:

```
 -> Processing approximately task 1409 of 1519 ...
 -> Processing approximately task 1217 of 1519 ...
 -> Processing approximately task 1425 of 1519 ...
Missing tag 'proc_obsd_17_40' from obsd_station_group AC.SRN. Skipped.
```

Could that be a reason why some events are missing?

Also could you give me permission to read your output files at /lustre/atlas1/geo111/world-shared/wenjie/DATA_RADICAL/data_processing? (test.* files)

**Comment by vivek-bala** [comment]
I ran the adjoint and adjoint_sum stages again. I get the same error again. Let me know how I can help debug.

**Comment by wjlei1990** [comment]
I opened the permission of the "test.o*" file to you.

Those "Missing tag 'proc_obsd_17_40' from obsd_station_group AC.SRN. Skipped." are OK. I also have those warning messages in my log file. It is because after data processing, some traces are thrown away since the response file might wrong(or some data quality issue). So when calculating adjoint sources, those traces will be missing(but the their station tag still exists in the data file). That's why it gives out the error message.

I checked your version of "pyasdf" and "pypaw" they are identical to the version I used...I also compared the files which may cause the different and they are identical...

One thing I am curious is [here](https://github.com/wjlei1990/pypaw/blob/master/pypaw/adjoint.py#L248):
```
        if self.mpi_mode and self.rank == 0:
            output_ds = ASDFDataSet(output_filename, mpi=False)
            if output_ds.events:
                output_ds.events = obsd_ds.events
            del output_ds
        if self.mpi_mode:
            self.comm.barrier()
```

This is the place where I write the event information. I am not sure if your excitation get into the condition. Maybe your `self.mpi_mode` is `False`... I think I need to run the code together with you and see what happens there...

**Comment by vivek-bala** [comment]
Thanks for checking the versions and files! Do you want to meetup on hangout sometime to give the complete run a try? I'm available after 5pm today, over the weekend (if required) and most of next week (except Monday, I'll be working with PSU). Let me know what time works best for you. I'll prioritize this issue over rest since its critical.

**Comment by wjlei1990** [comment]
Let's chat tomorrow. I have sent you emails to schedule the meeting.

**Comment by vivek-bala** [comment]
This issue is now resolved. We can run the entire analysis workflow. There was an incorrect boolean evaluation which is now resolved master of pypaw.

Thanks to Wenjie and all for the help in resolving this issue!
