### ISSUE TITLE
Year 2 use case with Michael

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/hpc-workflows#51]
To be started before visiting PSU

**Comment by mturilli** [comment]
Determine whether Michael has a student in Y2

**Comment by mturilli** [comment]
PSU had a meeting with Michael, collected requirement and is ready to start to populate the SRS document.

**Comment by Weiming-Hu** [comment]
We have created a doc to keep tracks of tasks and ideas.

https://docs.google.com/document/d/1uYtPy_VqoZ24JeU8qgTIUVzCmoCN35gSXFCQpqKXYP0/edit?usp=sharing

**Comment by Weiming-Hu** [comment]
Instead of reusing and incrementing stage 1 use case, @vivek-bala and I have agreed on starting a new doc for stage 2 use case, because I can foresee a major change in the workflow. However, we can still increment the SRS document because requirements will mostly remain similar.

FYI, here is the [comprehensive AnEn Use Case](https://docs.google.com/document/d/1kxX0sucCNJtbjAONr-yP4JtLz7KhOmj9wqATPM8kO3w/edit#heading=h.l5z8xtdth8uo) the integrates different stages of AnEn the proposed use cases.

**Comment by Weiming-Hu** [comment]
Update use [case workflow](https://docs.google.com/document/d/1uYtPy_VqoZ24JeU8qgTIUVzCmoCN35gSXFCQpqKXYP0/edit?usp=sharing).

Create [issues to do in CAnalogsV2](https://github.com/Weiming-Hu/CAnalogsV2/issues/36)

**Comment by vivek-bala** [comment]
Iterated on use case diagram - Added raw notes from meeting. Added workflow derived in meeting. Todo: Describe notation and define task as functions

**Comment by mturilli** [comment]
PSU iterated on the document. Ongoing.

**Comment by Weiming-Hu** [comment]
The first draft is done. File size estimation depending on the data input.
